[package]
name = "unlimited"
version = "0.0.2"
authors = ["Carl-Erwin Griffith <carl.erwin@gmail.com>"]


[[bin]]
doc = false
name = "unlimited"
path = "src/main.rs"

[dependencies]
clap = "*"
termion = "*"
serde_json = "*"
futures = "0.1.13"
tokio-core = "0.1.6"
tokio-io = "0.1.1"

[profile.release]
#lto = true
debug = true
opt-level = 3
