[package]
name = "unlimited"
version = "0.0.4"
authors = ["Carl-Erwin Griffith <carl.erwin@gmail.com>"]


[[bin]]
doc = false
name = "unlimited"
path = "src/main.rs"

[dependencies]
libc = "*"
clap = "*"
termion = "*"
ncurses = "5.91.0"

[profile.release]
#lto = true
debug = true
opt-level = 3
